version: '3.8'

services:
  web:
    build: ./
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    deploy:
      resources:
        limits:
          memory: 4G  
        reservations:
          memory: 2G
    restart: unless-stopped